sudo: required

language: generic

services:
  - docker

env:
  global:
    - IMAGE_NAME=mattvperry/donkeybot
    - REGISTRY=suchtilt.azurecr.io

install: true
before_script:
  - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" "$REGISTRY"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_script:
  - docker images

deploy:
  provider: script
  script: docker push "$REGISTRY/$IMAGE_NAME"
  on:
    branch: master