#!/bin/sh

. ./env.cfg

docker run \
    -e HUBOT_DISCORD_TOKEN=${HUBOT_DISCORD_TOKEN} \
    -e HUBOT_DISCORD_STATUS_MSG=${HUBOT_DISCORD_STATUS_MSG} \
    -e HUBOT_WOW_API_KEY=${HUBOT_WOW_API_KEY} \
    -e HUBOT_FORECAST_API_KEY=${HUBOT_FORECAST_API_KEY} \
    -e HUBOT_GOOGLE_CSE_KEY=${HUBOT_GOOGLE_CSE_KEY} \
    -e HUBOT_GOOGLE_CSE_ID=${HUBOT_GOOGLE_CSE_ID} \
    -d \
    --name donkeybot \
    donkeybot
